require('config.colorscheme')
require('config.completion')
require('config.colorizer')
require('config.statusline')
--require('config.windline')
--require('config.treesitter')
require('config.nvim-tree')
