#!/bin/sh

exec xautolock  -detectsleep -time 5 -locker "/home/willywonka/.config/i3/lock" -notify 30 -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'" &

exec xidlehook  --not-when-fullscreen --timer 300 "systemctl suspend" - &

exec xset s 720 &
